services:
  valve_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valve_api
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app-network

  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - valve_api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge